name: build-apk

on:
  push:
    branches:
      - dev
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  VERSION: v1.0.1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}

      - name: Install Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          build-tools: 34.0.0
          ndk: '21.4.7075529'
          cmake: '3.22.1'

      - name: Grant execute permission for Gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew assembleRelease  # 这将生成未签名的APK

      - name: List APK Output Directory
        run: ls app/build/outputs/apk/release/

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: app/build/outputs/apk/release/app-release-unsigned.apk  # 上传未签名APK

      - name: Generate Changelog
        run: echo "# Good things have arrived" > ${{ github.workspace }}-CHANGELOG.txt

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.VERSION }}  # 使用环境变量
          release_name: Release ${{ env.VERSION }}
          draft: false
          prerelease: false
        continue-on-error: true  # 即使出错也继续执行

      - name: Publish version
        if: steps.create_release.outcome == 'success'  # 只有在创建成功时执行
        uses: softprops/action-gh-release@v2.0.8
        with:
          tag_name: ${{ env.VERSION }}  # 添加 tag_name 参数
          body_path: ${{ github.workspace }}-CHANGELOG.txt
          files: |
            app/build/outputs/apk/release/app-release-unsigned.apk
